exports.responseMessage = {
    "PARAMETER_MISSING": "PARAMETER_MISSING",
    "INVALID_ACCESS_TOKEN": "INVALID_ACCESS_TOKEN",
    "WRONG_PASSWORD": "WRONG_PASSWORD",
    "ACTION_COMPLETE": "ACTION_COMPLETE",
    "SHOW_ERROR_MESSAGE": "SHOW_ERROR_MESSAGE",
    "ERROR_IN_EXECUTION": "ERROR_IN_EXECUTION",
    "INVALID_ACCESS": "INVALID_ACCESS",
    "EMAIL_NOT_EXISTS": "EMAIL_NOT_EXISTS",
    "USER_NOT_FOUND": "USER_NOT_FOUND",
    "SOMETHING_WENT_WRONG": "SOMETHING_WENT_WRONG",
};

exports.responseFlags = {
    PARAMETER_MISSING: 100,
    INVALID_ACCESS_TOKEN: 101,
    INVALID_ACCESS: 201,
    WRONG_PASSWORD: 201,
    ACTION_COMPLETE: 200,
    SHOW_ERROR_MESSAGE: 201,
    ERROR_IN_EXECUTION: 404,
    USER_NOT_FOUND: 201,
    EMAIL_NOT_EXISTS: 400
  };